# Only for local development

services:
  postgres:
    image: postgres:17.1
    container_name: postgres-products
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U sa -d products"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  postgres-data: